### ISSUE TITLE
Access Token and Space ID

### ISSUE THREAD

**Issue by DanielLvovsky** [ryanwiemer/rw#13]
I am having problems with running the project locally
how to setup the the access token and space id?

Here is the error: 

Error: Contentful space ID and access token need to be provided.

**Comment by ryanwiemer** [comment]
@DanielLvovsky This is my personal website and it expects specific content that I have setup in Contentful. It's not a template but if that is something you are interested in you can check out my Gatsby Starter:

https://github.com/ryanwiemer/gatsby-starter-gcn
